name: Rintro2023
channels:
  - conda-forge
  - bioconda
  - R
  - defaults
dependencies:
  - r-base=4.1.3
  - r-rmarkdown=2.14
  - r-tidyverse=1.3.1
  - r-pheatmap=1.0.12
  - r-codetools=0.2_19
  - r-upsetr=1.4.0
  - r-kernsmooth=2.23.20
