name: Rintro
channels:
  - conda-forge
  - bioconda
  - R
  - defaults
dependencies:
  - quarto
  - r-base
  - r-tidyverse
  - r-pheatmap=1.0.12
  - r-codetools=0.2.19
  - r-upsetr=1.4.0
  - r-kernsmooth=2.23.20
  - r-ggridges
  - r-ggrepel
  - r-ggthemes
  - r-kernsmooth