name: Rintro
channels:
  - conda-forge
  - bioconda
  - R
  - defaults
dependencies:
  - quarto=1.4
  - r-base=4.2.3
  - r-tidyverse=2.0.0
  - r-pheatmap=1.0.12
  - r-codetools=0.2.19
  - r-upsetr=1.4.0
  - r-kernsmooth=2.23.20
  - r-ggridges=0.5.6
  - r-ggrepel=0.9.4
  - r-ggthemes=5.1.0
  - r-kernsmooth=2.23