name: Rintro2HTML
run-name: ${{ github.actor }} is testing

on:
  push:
    branches: ["2023.03"] 


jobs:
  
  build:
    name: Conda Tests
    runs-on: ubuntu-latest
    defaults:
       run:
         shell: bash -l {0}
    container: node:latest

    steps:
      - name: Print shell information
        run: |
          echo "Shell: $SHELL"
          echo "Shell version: $($SHELL --version)"
          uname -a || true

      - uses: actions/checkout@v2
      - name: Check yaml
        run: |
          cat conda_config.yml || true
      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: conda_config.yml
          # environment-name: Rintro2023

      - name: List Available Environment
        shell: bash -l {0}
        run: micromamba list

      - name: Activate Environment
        run: micromamba activate Rintro2023

      - name: Check Installation
        run: |
          echo "after conda activate Rintro: PATH=$PATH;"
          which R || true
          R --version || true

      - name: Render R Markdown and Move Site
        run: | 
          Rscript -e "rmarkdown::render_site('rmd')"  
          # mv rmd/_site .

      - name: Show all files
        run: ls -Ral

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: |
            ./rmd/_site
            