name: Rintro2HTML
run-name: ${{ github.actor }} is testing

on:
  push:
    branches: ["thomas"] 

jobs:
  
  build:
    name: Conda Tests
    runs-on: ubuntu-latest
    defaults:
       run:
         shell: bash -l {0}
    container: node:latest

    steps:
      - name: Print shell information
        run: |
          echo "Shell: $SHELL"
          echo "Shell version: $($SHELL --version)"
          uname -a || true

      - uses: actions/checkout@v4
      - name: Check yaml
        run: |
          cat configs/conda.yml || true

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@main
        with:
          environment-file: configs/conda.yml

      - name: List Available Environment
        shell: bash -l {0}
        run: micromamba list

      - name: Activate Environment
        run: micromamba activate Rintro

      - name: Check Installation
        run: |
          echo "after conda activate Rintro: PATH=$PATH;"
          which R || true
          R --version || true

      - name: Installation non-conda packages 
        run: |
          Rscript -e 'install.packages(c("KernSmooth"), repos="https://cloud.r-project.org")'

      - name: Inspect .libPaths
        run: |
          Rscript -e '.libPaths()'



      - name: Check Quarto
        run: |
          which micromamba 
          micromamba --version
          which R
          R --version
          which quarto
          quarto --version
          ls -alR
        
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}