name: Rintro2HTML
run-name: ${{ github.actor }} is testing

on:
  push:
    branches: ["thomas"] 

jobs:
  
  build:
    name: Conda Tests
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
       run:
         shell: bash -l {0}
#    container: node:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install Conda environment with Micromamba
        uses: mamba-org/setup-micromamba@main
        with:
          environment-file: configs/conda.yml

      - name: Activate Environment
        run: micromamba activate Rintro

      - name: Check Installation
        run: |
          echo "after conda activate Rintro: PATH=$PATH;"
          which R || true
          R --version || true
          which micromamba || true 
          micromamba --version || true
          which quarto || true 
          quarto --version || true

      - name: Installation non-conda packages 
        run: |
          Rscript -e 'install.packages(c("KernSmooth"), repos="https://cloud.r-project.org")'
          Rscript -e '.libPaths()' || true
        
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}