name: Render Rintro to HTML
run-name: ${{ github.actor }} is testing

on:
  push:
    branches: [2023.03] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.1.3'
    - name: Install R packages
      run: Rscript -e "install.packages(c('rmarkdown', 'knitr', 'tidyverse', 'pheatmap','upsetr'))"
    - name: Render R Markdown and Move Site
      run: Rscript -e "rmarkdown::render_site('rmd')" ; mv rmd/_site .
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site

